export let seniors = [


            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Терешин",
                "firstName": "Владимир",
                "patronymic": "Владимирович",
                "dateBirthday": "1",
                "monthBirthday": "11",
                "yearBirthday": "1953",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Котлова",
                "firstName": "Александра",
                "patronymic": "Андреевна",
                "dateBirthday": "1",
                "monthBirthday": "11",
                "yearBirthday": "1937",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Бабушкин",
                "firstName": "Дмитрий",
                "patronymic": "Логинович",
                "dateBirthday": "2",
                "monthBirthday": "11",
                "yearBirthday": "1957",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Цветков",
                "firstName": "Святослав",
                "patronymic": "Олегович",
                "dateBirthday": "2",
                "monthBirthday": "11",
                "yearBirthday": "1990",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Тимофеев",
                "firstName": "Александр",
                "patronymic": "Дмитриевич",
                "dateBirthday": "3",
                "monthBirthday": "11",
                "yearBirthday": "1972",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Романов",
                "firstName": "Олег",
                "patronymic": "Борисович",
                "dateBirthday": "4",
                "monthBirthday": "11",
                "yearBirthday": "1978",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Аржанов",
                "firstName": "Вячеслав",
                "patronymic": "Геннадьевич",
                "dateBirthday": "6",
                "monthBirthday": "11",
                "yearBirthday": "1979",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Мишкин",
                "firstName": "Константин",
                "patronymic": "Александрович",
                "dateBirthday": "6",
                "monthBirthday": "11",
                "yearBirthday": "1990",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Анашкин",
                "firstName": "Александр",
                "patronymic": "Игоревич",
                "dateBirthday": "7",
                "monthBirthday": "11",
                "yearBirthday": "1992",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Шишкин",
                "firstName": "Сергей",
                "patronymic": "Александрович",
                "dateBirthday": "7",
                "monthBirthday": "11",
                "yearBirthday": "1962",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Сенина",
                "firstName": "Галина",
                "patronymic": "Александровна",
                "dateBirthday": "9",
                "monthBirthday": "11",
                "yearBirthday": "1949",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Славных",
                "firstName": "Анастасия",
                "patronymic": "Николаевна",
                "dateBirthday": "10",
                "monthBirthday": "11",
                "yearBirthday": "1991",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Бабаскина",
                "firstName": "Елена",
                "patronymic": "Валентиновна",
                "dateBirthday": "11",
                "monthBirthday": "11",
                "yearBirthday": "1974",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Михайлов",
                "firstName": "Олег",
                "patronymic": "Васильевич",
                "dateBirthday": "11",
                "monthBirthday": "11",
                "yearBirthday": "2001",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Вдович",
                "firstName": "Виталий",
                "patronymic": "Алексеевич",
                "dateBirthday": "12",
                "monthBirthday": "11",
                "yearBirthday": "1954",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Вести",
                "firstName": "Тамара",
                "patronymic": "Борисовна",
                "dateBirthday": "12",
                "monthBirthday": "11",
                "yearBirthday": "1952",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Комаров",
                "firstName": "Борис",
                "patronymic": "Александрович",
                "dateBirthday": "12",
                "monthBirthday": "11",
                "yearBirthday": "1989",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Чашкова",
                "firstName": "Надежда",
                "patronymic": "Ивановна",
                "dateBirthday": "13",
                "monthBirthday": "11",
                "yearBirthday": "1949",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Шешукова",
                "firstName": "Татьяна",
                "patronymic": "Валентиновна",
                "dateBirthday": "15",
                "monthBirthday": "11",
                "yearBirthday": "1955",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Докшина",
                "firstName": "Мария",
                "patronymic": "Юрьевна",
                "dateBirthday": "17",
                "monthBirthday": "11",
                "yearBirthday": "1986",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Дизер",
                "firstName": "Татьяна",
                "patronymic": "Геннадьевна",
                "dateBirthday": "18",
                "monthBirthday": "11",
                "yearBirthday": "1969",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Панов",
                "firstName": "Николай",
                "patronymic": "Васильевич",
                "dateBirthday": "18",
                "monthBirthday": "11",
                "yearBirthday": "1986",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Сафонов",
                "firstName": "Николай",
                "patronymic": "Михайлович",
                "dateBirthday": "18",
                "monthBirthday": "11",
                "yearBirthday": "1954",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Быбин",
                "firstName": "Владимир",
                "patronymic": "Павлович",
                "dateBirthday": "19",
                "monthBirthday": "11",
                "yearBirthday": "1963",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Ворона",
                "firstName": "Людмила",
                "dateBirthday": "20",
                "monthBirthday": "11",
                "yearBirthday": "1990",
                "gender": "ж",
                "comment1": "(отчество не указано)",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Перминов",
                "firstName": "Владимир",
                "patronymic": "Леонидович",
                "dateBirthday": "20",
                "monthBirthday": "11",
                "yearBirthday": "1955",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Кашаев",
                "firstName": "Николай",
                "patronymic": "Валериевич",
                "dateBirthday": "22",
                "monthBirthday": "11",
                "yearBirthday": "1976",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Рахимов",
                "firstName": "Иван",
                "patronymic": "Юрьевич",
                "dateBirthday": "24",
                "monthBirthday": "11",
                "yearBirthday": "1988",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Лугинский",
                "firstName": "Александр",
                "patronymic": "Анатольевич",
                "dateBirthday": "26",
                "monthBirthday": "11",
                "yearBirthday": "1950",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Зорина",
                "firstName": "Надежда",
                "patronymic": "Васильевна",
                "dateBirthday": "27",
                "monthBirthday": "11",
                "yearBirthday": "1954",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Казанцев",
                "firstName": "Алексей",
                "patronymic": "Владимирович",
                "dateBirthday": "28",
                "monthBirthday": "11",
                "yearBirthday": "1979",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Миняева",
                "firstName": "Ирина",
                "patronymic": "Владимировна",
                "dateBirthday": "29",
                "monthBirthday": "11",
                "yearBirthday": "1985",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Поярков",
                "firstName": "Сергей",
                "patronymic": "Николаевич",
                "dateBirthday": "29",
                "monthBirthday": "11",
                "yearBirthday": "1974",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Фролова",
                "firstName": "Любовь",
                "patronymic": "Николаевна",
                "dateBirthday": "1",
                "monthBirthday": "12",
                "yearBirthday": "1957",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Егоров",
                "firstName": "Дмитрий",
                "patronymic": "Иванович",
                "dateBirthday": "1",
                "monthBirthday": "12",
                "yearBirthday": "1975",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Бугаев",
                "firstName": "Артем",
                "patronymic": "Александрович",
                "dateBirthday": "2",
                "monthBirthday": "12",
                "yearBirthday": "1991",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Осипов",
                "firstName": "Артем",
                "patronymic": "Анатольевич",
                "dateBirthday": "5",
                "monthBirthday": "12",
                "yearBirthday": "1992",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Мелентьев",
                "firstName": "Антон",
                "patronymic": "Игоревич",
                "dateBirthday": "5",
                "monthBirthday": "12",
                "yearBirthday": "1996",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Плетенев",
                "firstName": "Леонид",
                "patronymic": "Зосимович",
                "dateBirthday": "6",
                "monthBirthday": "12",
                "yearBirthday": "1965",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Касимова",
                "firstName": "Софья",
                "patronymic": "Наилевна",
                "dateBirthday": "7",
                "monthBirthday": "12",
                "yearBirthday": "1988",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Мисько",
                "firstName": "Оксана",
                "patronymic": "Адамовна",
                "dateBirthday": "7",
                "monthBirthday": "12",
                "yearBirthday": "1977",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Лешакова",
                "firstName": "Галина",
                "patronymic": "Васильевна",
                "dateBirthday": "8",
                "monthBirthday": "12",
                "yearBirthday": "1962",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Ильина",
                "firstName": "Елена",
                "patronymic": "Валерьевна",
                "dateBirthday": "11",
                "monthBirthday": "12",
                "yearBirthday": "1981",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Еремина",
                "firstName": "Галина",
                "patronymic": "Федоровна",
                "dateBirthday": "12",
                "monthBirthday": "12",
                "yearBirthday": "1940",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Ячменев",
                "firstName": "Олег",
                "patronymic": "Владимирович",
                "dateBirthday": "12",
                "monthBirthday": "12",
                "yearBirthday": "1969",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Беленький",
                "firstName": "Дмитрий",
                "patronymic": "Николаевич",
                "dateBirthday": "13",
                "monthBirthday": "12",
                "yearBirthday": "1995",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Дьякова",
                "firstName": "Валентина",
                "patronymic": "Ивановна",
                "dateBirthday": "14",
                "monthBirthday": "12",
                "yearBirthday": "1940",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Сычев",
                "firstName": "Сергей",
                "patronymic": "Игоревич",
                "dateBirthday": "16",
                "monthBirthday": "12",
                "yearBirthday": "2000",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Жильцов",
                "firstName": "Игнатий",
                "patronymic": "Владимирович",
                "dateBirthday": "18",
                "monthBirthday": "12",
                "yearBirthday": "1989",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Хасанов",
                "firstName": "Ринат",
                "patronymic": "Станиславович",
                "dateBirthday": "18",
                "monthBirthday": "12",
                "yearBirthday": "1980",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Глушков",
                "firstName": "Алексей",
                "patronymic": "Иванович",
                "dateBirthday": "20",
                "monthBirthday": "12",
                "yearBirthday": "1942",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Маевский",
                "firstName": "Анатолий",
                "patronymic": "Михайлович",
                "dateBirthday": "20",
                "monthBirthday": "12",
                "yearBirthday": "1942",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Михай",
                "firstName": "Алена",
                "patronymic": "Бабачевна",
                "dateBirthday": "20",
                "monthBirthday": "12",
                "yearBirthday": "1987",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Слинкина",
                "firstName": "Нина",
                "patronymic": "Петровна",
                "dateBirthday": "20",
                "monthBirthday": "12",
                "yearBirthday": "1947",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Звозникова",
                "firstName": "Юлия",
                "patronymic": "Николаевна",
                "dateBirthday": "22",
                "monthBirthday": "12",
                "yearBirthday": "1982",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Назаренко",
                "firstName": "Александр",
                "patronymic": "Александрович",
                "dateBirthday": "22",
                "monthBirthday": "12",
                "yearBirthday": "1984",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Новосельцев",
                "firstName": "Владислав",
                "patronymic": "Валерьевич",
                "dateBirthday": "22",
                "monthBirthday": "12",
                "yearBirthday": "1982",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Гуляев",
                "firstName": "Кирилл",
                "patronymic": "Вячеславович",
                "dateBirthday": "23",
                "monthBirthday": "12",
                "yearBirthday": "1996",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Малютенко",
                "firstName": "Валерия",
                "patronymic": "Валентиновна",
                "dateBirthday": "23",
                "monthBirthday": "12",
                "yearBirthday": "1987",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Ананьина",
                "firstName": "Мария",
                "patronymic": "Васильевна",
                "dateBirthday": "24",
                "monthBirthday": "12",
                "yearBirthday": "1978",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Кошкаров",
                "firstName": "Иван",
                "patronymic": "Юрьевич",
                "dateBirthday": "24",
                "monthBirthday": "12",
                "yearBirthday": "1992",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Березовская",
                "firstName": "Анна",
                "patronymic": "Евсигнеевна",
                "dateBirthday": "25",
                "monthBirthday": "12",
                "yearBirthday": "1948",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Сумина",
                "firstName": "Александра",
                "patronymic": "Сергеевна",
                "dateBirthday": "25",
                "monthBirthday": "12",
                "yearBirthday": "1998",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Княжева",
                "firstName": "Олеся",
                "patronymic": "Юрьевна",
                "dateBirthday": "26",
                "monthBirthday": "12",
                "yearBirthday": "1993",
                "gender": "ж",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Щербаков",
                "firstName": "Максим",
                "patronymic": "Николаевич",
                "dateBirthday": "26",
                "monthBirthday": "12",
                "yearBirthday": "1977",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Видергольд",
                "firstName": "Александр",
                "patronymic": "Юрьевич",
                "dateBirthday": "29",
                "monthBirthday": "12",
                "yearBirthday": "1980",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Аитов",
                "firstName": "Салават",
                "patronymic": "Шайхидинович",
                "dateBirthday": "31",
                "monthBirthday": "12",
                "yearBirthday": "1959",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            },
            {
                "region": "ТЮМЕНСКАЯ",
                "nursingHome": "ВИНЗИЛИ",
                "lastName": "Кныш",
                "firstName": "Александр",
                "patronymic": "Васильевич",
                "dateBirthday": "31",
                "monthBirthday": "12",
                "yearBirthday": "1970",
                "gender": "м",
                "dateNameDay": "0",
                "monthNameDay": "0",
                "isRestricted": "false"
            }
        
        
]
