export let seniors = [
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Александрова",
            "firstName": "Наталия",
            "patronymic": "Петровна",
            "monthBirthday": "11",
            "dateBirthday": "9",
            "yearBirthday": "1960",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Алексеев",
            "firstName": "Анатолий",
            "patronymic": "Павлович",
            "monthBirthday": "4",
            "dateBirthday": "15",
            "yearBirthday": "1965",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Банадысев",
            "firstName": "Василий",
            "patronymic": "Александрович",
            "monthBirthday": "6",
            "dateBirthday": "17",
            "yearBirthday": "1951",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Вдовин",
            "firstName": "Анатолий",
            "patronymic": "Гаврилович",
            "monthBirthday": "4",
            "dateBirthday": "6",
            "yearBirthday": "1953",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Власенко",
            "firstName": "Вячеслав",
            "patronymic": "Анатольевич",
            "monthBirthday": "3",
            "dateBirthday": "25",
            "yearBirthday": "1971",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Воробей",
            "firstName": "Павел",
            "patronymic": "Алексеевич",
            "monthBirthday": "10",
            "dateBirthday": "11",
            "yearBirthday": "1951",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Герасимова",
            "firstName": "Ольга",
            "patronymic": "Александровна",
            "monthBirthday": "1",
            "dateBirthday": "12",
            "yearBirthday": "1966",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Голдобов",
            "firstName": "Сергей",
            "patronymic": "Викторович",
            "monthBirthday": "7",
            "dateBirthday": "1",
            "yearBirthday": "1962",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Голикова",
            "firstName": "Надежда",
            "patronymic": "Петровна",
            "monthBirthday": "4",
            "dateBirthday": "30",
            "yearBirthday": "1937",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Громов",
            "firstName": "Николай",
            "patronymic": "Андреевич",
            "monthBirthday": "1",
            "dateBirthday": "26",
            "yearBirthday": "1953",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Давыдова",
            "firstName": "Зинаида",
            "patronymic": "Сергеевна",
            "monthBirthday": "8",
            "dateBirthday": "20",
            "yearBirthday": "1954",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Ефремов",
            "firstName": "Александр",
            "patronymic": "Иванович",
            "monthBirthday": "4",
            "dateBirthday": "7",
            "yearBirthday": "1956",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Жирякова",
            "firstName": "Анна",
            "patronymic": "Ивановна",
            "monthBirthday": "6",
            "dateBirthday": "10",
            "yearBirthday": "1946",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Ильин",
            "firstName": "Сергей",
            "patronymic": "Николаевич",
            "monthBirthday": "12",
            "dateBirthday": "24",
            "yearBirthday": "1964",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Калибин",
            "firstName": "Сергей",
            "patronymic": "Николаевич",
            "monthBirthday": "10",
            "dateBirthday": "1",
            "yearBirthday": "1987",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Кирсанов",
            "firstName": "Николай",
            "patronymic": "Васильевич",
            "monthBirthday": "12",
            "dateBirthday": "14",
            "yearBirthday": "1959",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Клинова",
            "firstName": "Марина",
            "patronymic": "Александровна",
            "monthBirthday": "4",
            "dateBirthday": "21",
            "yearBirthday": "1982",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Козаченко",
            "firstName": "Нина",
            "patronymic": "Антоновна",
            "monthBirthday": "6",
            "dateBirthday": "18",
            "yearBirthday": "1945",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Королев",
            "firstName": "Владимир",
            "patronymic": "Викторович",
            "monthBirthday": "12",
            "dateBirthday": "7",
            "yearBirthday": "1942",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Красавин",
            "firstName": "Александр",
            "patronymic": "Владимирович",
            "monthBirthday": "12",
            "dateBirthday": "8",
            "yearBirthday": "1967",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Куприн",
            "firstName": "Михаил",
            "patronymic": "Юрьевич",
            "monthBirthday": "11",
            "dateBirthday": "24",
            "yearBirthday": "1977",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Логинова",
            "firstName": "Тамара",
            "patronymic": "Андреевна",
            "monthBirthday": "9",
            "dateBirthday": "20",
            "yearBirthday": "1945",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Максимов",
            "firstName": "Александр",
            "patronymic": "Юрьевич",
            "monthBirthday": "11",
            "dateBirthday": "16",
            "yearBirthday": "1961",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Марышев",
            "firstName": "Александр",
            "patronymic": "Николаевич",
            "monthBirthday": "8",
            "dateBirthday": "11",
            "yearBirthday": "1969",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Мельников",
            "firstName": "Андрей",
            "patronymic": "Николаевич",
            "monthBirthday": "6",
            "dateBirthday": "9",
            "yearBirthday": "1973",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Мокеев",
            "firstName": "Владимир",
            "patronymic": "Васильевич",
            "monthBirthday": "12",
            "dateBirthday": "4",
            "yearBirthday": "1954",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Молчанова",
            "firstName": "Ольга",
            "patronymic": "Евгеньевна",
            "monthBirthday": "9",
            "dateBirthday": "25",
            "yearBirthday": "1974",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Окунева",
            "firstName": "Жанна",
            "patronymic": "Викторовна",
            "monthBirthday": "3",
            "dateBirthday": "15",
            "yearBirthday": "1966",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Орлов",
            "firstName": "Александр",
            "patronymic": "Петрович",
            "monthBirthday": "7",
            "dateBirthday": "13",
            "yearBirthday": "1936",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Павлова",
            "firstName": "Валентина",
            "patronymic": "Николаевна",
            "monthBirthday": "2",
            "dateBirthday": "16",
            "yearBirthday": "1979",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Парфентьев",
            "firstName": "Леонид",
            "patronymic": "Викторович",
            "monthBirthday": "6",
            "dateBirthday": "22",
            "yearBirthday": "1988",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Пискунова",
            "firstName": "Оксана",
            "patronymic": "Александровна",
            "monthBirthday": "10",
            "dateBirthday": "18",
            "yearBirthday": "1982",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Поршнева",
            "firstName": "Елена",
            "patronymic": "Павловна",
            "monthBirthday": "3",
            "dateBirthday": "13",
            "yearBirthday": "1980",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Родионов",
            "firstName": "Владимир",
            "patronymic": "Александрович",
            "monthBirthday": "5",
            "dateBirthday": "18",
            "yearBirthday": "1953",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Рыжакова",
            "firstName": "Марина",
            "patronymic": "Юрьевна",
            "monthBirthday": "11",
            "dateBirthday": "4",
            "yearBirthday": "1967",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Рыжакова",
            "firstName": "Светлана",
            "patronymic": "Юрьевна",
            "monthBirthday": "11",
            "dateBirthday": "4",
            "yearBirthday": "1967",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Саберова",
            "firstName": "Рабия",
            "patronymic": "Анвяровна",
            "monthBirthday": "5",
            "dateBirthday": "29",
            "yearBirthday": "1945",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Сашков",
            "firstName": "Николай",
            "patronymic": "Андреевич",
            "monthBirthday": "6",
            "dateBirthday": "25",
            "yearBirthday": "1978",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Сизова",
            "firstName": "Татьяна",
            "patronymic": "Ивановна",
            "monthBirthday": "6",
            "dateBirthday": "20",
            "yearBirthday": "1957",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Стрелкова",
            "firstName": "Валентина",
            "patronymic": "Владимировна",
            "monthBirthday": "1",
            "dateBirthday": "11",
            "yearBirthday": "1953",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Таймазова",
            "firstName": "Зоя",
            "patronymic": "Абдуллаевна",
            "monthBirthday": "9",
            "dateBirthday": "19",
            "yearBirthday": "1957",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Татаркин",
            "firstName": "Владимир",
            "patronymic": "Геннадьевич",
            "monthBirthday": "4",
            "dateBirthday": "22",
            "yearBirthday": "1989",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Тихонов",
            "firstName": "Сергей",
            "patronymic": "Евгеньевич",
            "monthBirthday": "4",
            "dateBirthday": "3",
            "yearBirthday": "1950",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Федотов",
            "firstName": "Валерий",
            "patronymic": "Николаевич",
            "monthBirthday": "1",
            "dateBirthday": "29",
            "yearBirthday": "1963",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Федотов",
            "firstName": "Владимир",
            "patronymic": "Анатольевич",
            "monthBirthday": "8",
            "dateBirthday": "24",
            "yearBirthday": "1973",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Хорьков",
            "firstName": "Геннадий",
            "patronymic": "Геннадьевич",
            "monthBirthday": "12",
            "dateBirthday": "21",
            "yearBirthday": "1969",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Челышев",
            "firstName": "Иван",
            "patronymic": "Васильевич",
            "monthBirthday": "1",
            "dateBirthday": "16",
            "yearBirthday": "1940",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "НОВЛЯНКА",
            "lastName": "Чеснокова",
            "firstName": "Светлана",
            "patronymic": "Геннадьевна",
            "monthBirthday": "6",
            "dateBirthday": "30",
            "yearBirthday": "1962",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Аблизин",
            "firstName": "Анатолий",
            "patronymic": "Николаевич",
            "monthBirthday": "1",
            "dateBirthday": "1",
            "yearBirthday": "1947",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Антипова",
            "firstName": "Наталья",
            "patronymic": "Владимировна",
            "monthBirthday": "4",
            "dateBirthday": "9",
            "yearBirthday": "1975",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Баранов",
            "firstName": "Александр",
            "patronymic": "Александрович",
            "monthBirthday": "6",
            "dateBirthday": "26",
            "yearBirthday": "1941",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Башкирова",
            "firstName": "Нина",
            "patronymic": "Егоровна",
            "monthBirthday": "10",
            "dateBirthday": "5",
            "yearBirthday": "1934",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Виташова",
            "firstName": "Екатерина",
            "patronymic": "Федоровна",
            "monthBirthday": "11",
            "dateBirthday": "30",
            "yearBirthday": "1929",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Горбушина",
            "firstName": "Тамара",
            "patronymic": "Аполлосовна",
            "monthBirthday": "3",
            "dateBirthday": "19",
            "yearBirthday": "1936",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Горюнов",
            "firstName": "Александр",
            "patronymic": "Павлович",
            "monthBirthday": "2",
            "dateBirthday": "4",
            "yearBirthday": "1949",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Горячкина",
            "firstName": "Нина",
            "patronymic": "Михайловна",
            "monthBirthday": "7",
            "dateBirthday": "10",
            "yearBirthday": "1939",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Громов",
            "firstName": "Олег",
            "patronymic": "Алексеевич",
            "monthBirthday": "12",
            "dateBirthday": "25",
            "yearBirthday": "1966",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Есефьев",
            "firstName": "Виктор",
            "patronymic": "Александрович",
            "monthBirthday": "12",
            "dateBirthday": "31",
            "yearBirthday": "1954",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Загладин",
            "firstName": "Виктор",
            "patronymic": "Викторович",
            "monthBirthday": "3",
            "dateBirthday": "30",
            "yearBirthday": "1942",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Захаров",
            "firstName": "Алексей",
            "patronymic": "Иванович",
            "monthBirthday": "3",
            "dateBirthday": "22",
            "yearBirthday": "1948",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Игнатьев",
            "firstName": "Вячеслав",
            "patronymic": "Ильич",
            "monthBirthday": "2",
            "dateBirthday": "16",
            "yearBirthday": "1940",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Исаева",
            "firstName": "Галина",
            "patronymic": "Алексеевна",
            "monthBirthday": "1",
            "dateBirthday": "31",
            "yearBirthday": "1952",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Киселев",
            "firstName": "Владимир",
            "patronymic": "Дмитриевич",
            "monthBirthday": "3",
            "dateBirthday": "19",
            "yearBirthday": "1957",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Колесников",
            "firstName": "Валерий",
            "patronymic": "Яковлевич",
            "monthBirthday": "2",
            "dateBirthday": "2",
            "yearBirthday": "1948",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Коробихин",
            "firstName": "Владимир",
            "patronymic": "Васильевич",
            "monthBirthday": "6",
            "dateBirthday": "2",
            "yearBirthday": "1948",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Красов",
            "firstName": "Олег",
            "patronymic": "Евгеньевич",
            "monthBirthday": "5",
            "dateBirthday": "19",
            "yearBirthday": "1951",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Кузнецова",
            "firstName": "Татьяна",
            "patronymic": "Савельевна",
            "monthBirthday": "2",
            "dateBirthday": "17",
            "yearBirthday": "1932",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Лапшин",
            "firstName": "Николай",
            "patronymic": "Иванович",
            "monthBirthday": "9",
            "dateBirthday": "21",
            "yearBirthday": "1985",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Лукьянов",
            "firstName": "Евгений",
            "patronymic": "Григорьевич",
            "monthBirthday": "4",
            "dateBirthday": "9",
            "yearBirthday": "1951",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Майоров",
            "firstName": "Михаил",
            "patronymic": "Викторович",
            "monthBirthday": "11",
            "dateBirthday": "21",
            "yearBirthday": "1959",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Максимов",
            "firstName": "Максим",
            "patronymic": "Анатольевич",
            "monthBirthday": "2",
            "dateBirthday": "13",
            "yearBirthday": "1974",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Малышева",
            "firstName": "Валентина",
            "patronymic": "Ивановна",
            "monthBirthday": "9",
            "dateBirthday": "10",
            "yearBirthday": "1943",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Маркова",
            "firstName": "Антонина",
            "patronymic": "Павловна",
            "monthBirthday": "12",
            "dateBirthday": "5",
            "yearBirthday": "1937",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Морозов",
            "firstName": "Владимир",
            "patronymic": "Васильевич",
            "monthBirthday": "10",
            "dateBirthday": "24",
            "yearBirthday": "1953",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Новиков",
            "firstName": "Виктор",
            "patronymic": "Васильевич",
            "monthBirthday": "3",
            "dateBirthday": "5",
            "yearBirthday": "1959",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Помещиков",
            "firstName": "Сергей",
            "patronymic": "Васильевич",
            "monthBirthday": "6",
            "dateBirthday": "13",
            "yearBirthday": "1952",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Прозоров",
            "firstName": "Анатолий",
            "patronymic": "Леонидович",
            "monthBirthday": "8",
            "dateBirthday": "18",
            "yearBirthday": "1966",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Пронин",
            "firstName": "Владимир",
            "patronymic": "Иванович",
            "monthBirthday": "11",
            "dateBirthday": "7",
            "yearBirthday": "1959",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Пугина",
            "firstName": "Галина",
            "patronymic": "Федоровна",
            "monthBirthday": "7",
            "dateBirthday": "7",
            "yearBirthday": "1940",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Родионов",
            "firstName": "Василий",
            "patronymic": "Федорович",
            "monthBirthday": "2",
            "dateBirthday": "21",
            "yearBirthday": "1953",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Романов",
            "firstName": "Владимир",
            "patronymic": "Васильевич",
            "monthBirthday": "5",
            "dateBirthday": "19",
            "yearBirthday": "1954",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Сабаев",
            "firstName": "Владимир",
            "patronymic": "Константинович",
            "monthBirthday": "6",
            "dateBirthday": "11",
            "yearBirthday": "1978",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Салыгин",
            "firstName": "Николай",
            "patronymic": "Олегович",
            "monthBirthday": "11",
            "dateBirthday": "7",
            "yearBirthday": "1962",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Середа",
            "firstName": "Василий",
            "patronymic": "Юрьевич",
            "monthBirthday": "8",
            "dateBirthday": "26",
            "yearBirthday": "1961",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Сизова",
            "firstName": "Ирина",
            "patronymic": "Юрьевна",
            "monthBirthday": "2",
            "dateBirthday": "25",
            "yearBirthday": "1986",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Сорокин",
            "firstName": "Николай",
            "patronymic": "Николаевич",
            "monthBirthday": "12",
            "dateBirthday": "4",
            "yearBirthday": "1941",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Спирина",
            "firstName": "Мария",
            "patronymic": "Алексеевна",
            "monthBirthday": "8",
            "dateBirthday": "28",
            "yearBirthday": "1923",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Степанова",
            "firstName": "Галина",
            "patronymic": "Деомидовна",
            "monthBirthday": "3",
            "dateBirthday": "23",
            "yearBirthday": "1939",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Степанова",
            "firstName": "Евгения",
            "patronymic": "Андреевна",
            "monthBirthday": "1",
            "dateBirthday": "24",
            "yearBirthday": "1942",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Сторонкин",
            "firstName": "Александр",
            "patronymic": "Васильевич",
            "monthBirthday": "1",
            "dateBirthday": "4",
            "yearBirthday": "1936",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Сторонкина",
            "firstName": "Ольга",
            "patronymic": "Макарьевна",
            "monthBirthday": "9",
            "dateBirthday": "3",
            "yearBirthday": "1935",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Суворкина",
            "firstName": "Зинаида",
            "patronymic": "Петровна",
            "monthBirthday": "3",
            "dateBirthday": "4",
            "yearBirthday": "1931",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Ташогло",
            "firstName": "Любовь",
            "patronymic": "Федоровна",
            "monthBirthday": "12",
            "dateBirthday": "6",
            "yearBirthday": "1954",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Токарев",
            "firstName": "Валерий",
            "patronymic": "Викторович",
            "monthBirthday": "7",
            "dateBirthday": "4",
            "yearBirthday": "1962",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Токарева",
            "firstName": "Юлия",
            "patronymic": "Григорьевна",
            "monthBirthday": "3",
            "dateBirthday": "3",
            "yearBirthday": "1972",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Тулюсин",
            "firstName": "Владимир",
            "patronymic": "Иванович",
            "monthBirthday": "5",
            "dateBirthday": "3",
            "yearBirthday": "1936",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Федотова",
            "firstName": "Анна",
            "patronymic": "Васильевна",
            "monthBirthday": "9",
            "dateBirthday": "28",
            "yearBirthday": "1944",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Хименкова",
            "firstName": "Клавдия",
            "patronymic": "Петровна",
            "monthBirthday": "7",
            "dateBirthday": "15",
            "yearBirthday": "1940",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Чигирова",
            "firstName": "Жанна",
            "patronymic": "Ефимовна",
            "monthBirthday": "3",
            "dateBirthday": "17",
            "yearBirthday": "1935",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Шабордина",
            "firstName": "Тамара",
            "patronymic": "Васильевна",
            "monthBirthday": "11",
            "dateBirthday": "7",
            "yearBirthday": "1940",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Шмелев",
            "firstName": "Александр",
            "patronymic": "Васильевич",
            "monthBirthday": "9",
            "dateBirthday": "8",
            "yearBirthday": "1945",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Шульгин",
            "firstName": "Станислав",
            "patronymic": "Васильевич",
            "monthBirthday": "3",
            "dateBirthday": "17",
            "yearBirthday": "1937",
            "gender": "м",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        },
        {
            "region": "ВЛАДИМИРСКАЯ",
            "nursingHome": "ПЕРЕЛОЖНИКОВО",
            "lastName": "Шулепина",
            "firstName": "Татьяна",
            "patronymic": "Александровна",
            "monthBirthday": "4",
            "dateBirthday": "5",
            "yearBirthday": "1964",
            "gender": "ж",
            "dateNameDay": "0",
            "monthNameDay": "0",
            "isRestricted": "false"
        }
    ]
